version: 2.1

aliases:
  - &attach_workspace
    attach_workspace:
      at: ~/repo
  - &restore_cache
    restore_cache:
      keys:
        - v1-cargo-{{ checksum "Cargo.lock" }}

executors:
  rust_exec:
    docker:
      - image: rust:latest
    working_directory: ~/repo

jobs:
  setup:
    executor: rust_exec
    steps:
      - checkout
      - run:
          name: Rust version info
          command: rustc --version; cargo --version
      - *restore_cache
      - run:
          name: Install cargo dependencies
          command: cargo fetch
      - save_cache:
          key: v1-cargo-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry
            - /usr/local/cargo/git
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    executor: rust_exec
    steps:
      - *attach_workspace
      - *restore_cache
      - run:
          name: Make mask available for certain test suites that depend on it
          command: echo 'export PATH="$PATH:~/repo/target/debug"' >> $BASH_ENV
      - run:
          name: Install latest node from PPA
          command: apt-get update && apt-get install -y curl software-properties-common && curl -sL https://deb.nodesource.com/setup_12.x | bash - && apt-get install nodejs
      - run:
          name: Install other runtimes
          command: apt-get update && apt-get install -y ruby-full php
      - run:
          name: Run tests
          command: cargo test --verbose --frozen

workflows:
  pr_test:
    jobs:
      - setup
      - test:
          requires:
            - setup
