name: New Release

on:
  release:
    types: [created]

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch dependencies
        run: cargo fetch
      - name: Build in release mode
        run: cargo build --release --frozen --target x86_64-unknown-linux-gnu
      - name: Add the version tag to the binary name
        run: |
          VERSION_TAG=$(jq --raw-output '.release.tag_name' "$GITHUB_EVENT_PATH")
          TARGET=x86_64-unknown-linux-gnu
          NAME=mask-$VERSION_TAG-$TARGET
          mkdir $NAME
          mv ./target/$TARGET/release/mask ./$NAME/mask
          chmod +x ./$NAME/mask
          zip -r $NAME.zip $NAME
      - name: Attach the binary to the release
        uses: ./.github/actions/attach-release-assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          assets: ./*.zip

  release-macos-aarch64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: aarch64-apple-darwin
          default: true
      - name: Fetch dependencies
        run: cargo fetch
      - name: Build in release mode
        run: |
          SDKROOT=$(xcrun -sdk macosx --show-sdk-path)
          MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx --show-sdk-platform-version)
          cargo build --release --frozen --target aarch64-apple-darwin
      - name: Add the version tag to the binary name
        run: |
          VERSION_TAG=$(jq --raw-output '.release.tag_name' "$GITHUB_EVENT_PATH")
          TARGET=aarch64-apple-darwin
          NAME=mask-$VERSION_TAG-$TARGET
          mkdir $NAME
          mv ./target/$TARGET/release/mask ./$NAME/mask
          chmod +x ./$NAME/mask
          zip -r $NAME.zip $NAME
      # NOTE: cannot use the attach-release-assets action because macOS doesn't support docker-based actions.
      # Luckily we can just run the bash script directly.
      - name: Attach the binary to the release
        run: ./.github/actions/attach-release-assets/run.sh ./*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-macos-x86-64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
      - name: Fetch dependencies
        run: cargo fetch
      - name: Build in release mode
        run: cargo build --release --frozen --target x86_64-apple-darwin
      - name: Add the version tag to the binary name
        run: |
          VERSION_TAG=$(jq --raw-output '.release.tag_name' "$GITHUB_EVENT_PATH")
          TARGET=x86_64-apple-darwin
          NAME=mask-$VERSION_TAG-$TARGET
          mkdir $NAME
          mv ./target/$TARGET/release/mask ./$NAME/mask
          chmod +x ./$NAME/mask
          zip -r $NAME.zip $NAME
      # NOTE: cannot use the attach-release-assets action because macOS doesn't support docker-based actions.
      # Luckily we can just run the bash script directly.
      - name: Attach the binary to the release
        run: ./.github/actions/attach-release-assets/run.sh ./*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-homebrew:
    needs: release-macos-x86-64
    runs-on: ubuntu-latest
    steps:
      - name: Bump homebrew-core formula
        uses: mislav/bump-homebrew-formula-action@v1
        if: "!contains(github.ref, '-')" # skip prereleases
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        with:
          # Sends a PR to homebrew-core to update the formula
          formula-name: mask

  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch dependencies
        run: cargo fetch
      - name: Build in release mode
        run: cargo build --release --frozen --target x86_64-pc-windows-msvc
      - name: Add the version tag to the binary name
        shell: bash
        run: |
          VERSION_TAG=$(jq --raw-output '.release.tag_name' "$GITHUB_EVENT_PATH")
          TARGET=x86_64-pc-windows-msvc
          NAME=mask-$VERSION_TAG-$TARGET
          mkdir $NAME
          mv ./target/$TARGET/release/mask.exe ./$NAME/mask.exe
          7z a $NAME.zip $NAME
      # NOTE: cannot use the attach-release-assets action because windows doesn't support docker-based actions.
      # Luckily we can just run the bash script directly.
      - name: Attach the binary to the release
        shell: bash
        run: ./.github/actions/attach-release-assets/run.sh ./*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
